### DISCUSSION TITLE
Running Flux in OpenShift

### DISCUSSION THREAD

**Discussion by milroy** [flux-framework/flux-core#3102] [General]
I've gotten a simple test setup working that runs Flux in pods managed by OpenShift.  I used a deployment for replicating the pods to simulate Flux instances running across multiple nodes.  The config is essentially the same as a Kubernetes spec:

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: flux
  replicas: 2
  template:
    metadata:
      labels:
        app: flux
    spec:
      containers:
      - name: flux
        image: fluxrm/flux-sched:latest
        command: ["sleep"]
        args: ["infinity"]
        ports:
        - containerPort: 8050
```

Note the `command` and `args` parameters.  These allow the containers to keep running, otherwise they will exit immediately upon container startup. Now the bootstrap config is as you would expect if the containers were physical hosts (i.e. use the pod IPs, NICs, and names):

```TOML
[bootstrap]
hosts = [ { host="flux-deployment-1-q579j", bind="tcp://eth0:8050", connect="tcp://10.130.2.69:8050" }, { host="flux-deployment-1-tnnzb", bind="tcp://eth0:8050", connect="tcp://10.130.2.70:8050" }, ]
```

To start the Flux instances issue the following command in each container:

```bash
$ flux start -o,--config=/home/fluxuser/config
```

Now to test that they can communicate, run the following on rank0:

```bash
ƒ(s=2,d=0) fluxuser@flux-deployment-1-q579j:~$ flux exec -r all hostname
flux-deployment-1-q579j
flux-deployment-1-tnnzb
ƒ(s=2,d=0) fluxuser@flux-deployment-1-q579j:~$
```
