### DISCUSSION TITLE
Signaling jobs before their allocation expires

### DISCUSSION THREAD

**Discussion by SteVwonder** [flux-framework/flux-core#3259] [Design]
How do we want to support the functional equivalent of Slurm's `--signal=sig_num>[@<sig_time>]` argument, which is defined as:

> When a job is within `sig_time` seconds of its end time, send it the signal `sig_num`.

Related work: [libyogrt](https://github.com/LLNL/libyogrt)

**Comment by SteVwonder** [comment]
My initial thought here is to create a job shell plugin that is in charge of setting up a timer callback and then signalling the job processes at the appropriate time. This information could be specified in jobspec via a user attribute.  Maybe `attributes.user.signal`?

Strawman example:
```yaml
- attributes:
    user:
      signal:
        time: 60s
        number: USR1
```

Where time is an [FSD](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_23.html), and number is either an int or one of the POSIX signals without the SIG prefix.

**Reply by SteVwonder** [reply]
A slight alternative could be:

```yaml
- attributes:
    user:
      signal-time-remaining:
        when: 60s
        how: USR1
```
