### DISCUSSION TITLE
Using hierarchical YAML (or YAML unions/merges) in lieu of #FLUX in batch scripts

### DISCUSSION THREAD

**Discussion by SteVwonder** [flux-framework/flux-core#3278] [Ideas]
## Problem

Users typically have a common set of settings/attributes that they want to apply to every job in their workflow.  Common things include `bank`, `queue`, and `walltime`.  In Slurm, LSF, and many many other schedulers, they handle this by putting `#SCHEDNAME --cli-option value` directives at the top of the batch scripts.  On more exotic systems that include burst buffers, the staging commands also make their way into the top of the batch script as a `#` directive.

I don't think we ever really intended or wanted to special case "batch scripts" and read `#FLUX` directives from the top of the file to include in the jobspec.  Without ruling that out as a possibility, I was thinking of an alternative.

## Idea

Allow the user to provide YAML file(s) that serve as the "base" jobspec(s) layer(s).  The `flux mini` commands would then build the "top-level" YAML jobspec and apply a union/merge/flattening of the layers of YAML.

### my-campaign1.yaml
```yaml
attributes:
  system:
    bank: tooBigToFail
    queue: batch
    cwd: "$HOME/campaign1/"
    duration: 12h
    environment:
        CAMPAIGN: 1
  user:
    campaign: 1
```

### staging.yaml
```yaml
attributes:
  system:
    data-staging:
      - stage-in:
           file: $HOME/foo
```

### Illustrative Run lines
Submit a job with an included yaml but override the walltime in the "base" jobspec to only by 5 minutes:
`flux mini run --include my-campaign1.yaml -N1 -n1 -t 5m prep.exe`
Submit a job but include two yamls (latter includes take precedence over former includes):
`flux mini run --include my-campaign1.yaml --include staging.yaml -N4 -n16 run.exe`
Submit a job with an included yaml but override the queue:
`flux mini run --include my-campaign1.yaml -N1 -n16 --setattr system.queue=viz viz.exe`

## Reference Implementations of the Merge/Union/Flattening

- Hierarchical Yaml Config in Python: https://github.com/zerwes/hiyapyco
- Union Yaml in Haskell: https://hackage.haskell.org/package/yaml-union
- SO solution in a couple of lines in python: https://stackoverflow.com/a/47425751
- yq: https://mikefarah.gitbook.io/yq/commands/merge
