### DISCUSSION TITLE
flux jobspec v2 discussion, subsystem queries, implicit scoping

### DISCUSSION THREAD

**Discussion by trws** [flux-framework/flux-core#5785] [Design]
This is use-case 1.2 from our valid jobspec examples, reworked to use the
nesting setup @vsoch was proposing (roughly at least), this cuts a whole lot of
complexity, and yet it's easy to machine this into canonical:
```yaml
version: 999
tasks:
  - command: [ "flux", "start" ]
    count:
      min: 3
      max: 30
    resources:
    - type: node
      count: 1
attributes:
  system:
    duration: 3600.
    cwd: "/home/flux"
    environment:
      HOME: "/home/flux"

```

Here are some options for subsystem syntax for a rabbit:

3 nodes, all of which connect to the same rabbit by a storage link, no
limitation on number but that's implicitly one right now:
```yaml
version: 999
resources:
  - type: slot
    count: 3
    label: default
    with:
      - type: node
        count: 1
        with:
        - edge: storage
          label: rbt
  - type: rabbit
    label: rbt
    count: 1
tasks:
  - command: [ "flux", "start" ]
    slot: default
    count:
      per_slot: 1
attributes:
  system:
    duration: 3600.
    cwd: "/home/flux"
    environment:
      HOME: "/home/flux"
```

3 nodes, all of which connect to _some rabbit_ not necessarily the same one, do
we want to have different ones for near-node vs ephemeral lustre? Honestly I'm
not sure:
```yaml
version: 999
resources:
  - type: slot
    count: 3
    label: default
    with:
      - type: node
        count: 1
        with:
        - edge: storage
          type: rabbit
tasks:
  - command: [ "flux", "start" ]
    slot: default
    count:
      per_slot: 1
attributes:
  system:
    duration: 3600.
    cwd: "/home/flux"
    environment:
      HOME: "/home/flux"
```

Ping: @tpatki, @milroy, @jameshcorbett, @rountree

**Comment by vsoch** [comment]
Here is the modified variant I'm using, which is basically that - resources needed for a task.

```yaml
version: 1
resources:
- count: 2
  type: node
  with:
  - count: 1
    label: default
    type: slot
    with:
    - count: 2
      type: core
tasks:
- command:
  - ior
  slot: default
  count:
    per_slot: 1
  resources:
    io:
      match:
      - type: shm
```
The only difference from the above is that I'm scoping it to a named subsystem, and that is primarily for my implementation to be able to match it to the subsystem "io" and then use the custom algorithm defined there for it (subsystems might have different matching algorithms, or more explicitly - "the thing that you do" when you stumble on its edge in the graph (and have a connection to that subsystem graph).  The above says "When you find this edge for "io" while traversing a slot, just match that storage type "shared memory." It's dumb and simple but will be enough to reproduce our first descriptive experiments (that were done from an image selection standpoint) now using the scheduler.

**Reply by trws** [reply]
I think it ends up being isomorphic, the `edge:` key in mine is meant to convey essentially the same information as the `io:` key here if I understand you right.  It's just per-edge I guess rather than per-match?

How does this one know where to start looking for shm from, or is it a completely separate resource that doesn't have a graph connection to the nodes?

**Reply by vsoch** [reply]
Yep that looks about right. I just put it with the slot because (conceptually) that is alongside the application.

"shm" would be an edge from the node in the containment - when the subsystem is added, it has a reference to the edge it connects to, and then is [added to the dominant subsystem graph](https://github.com/converged-computing/rainbow/blob/bf92d293ce531e682685477f729d18f5857059d4/plugins/backends/memory/subsystem.go#L181-L212). 

You would start looking when you are parsing a jobspec slot "does my containment graph satisfy what this application needs"? And part of the slot definition includes the subsystem resource. You'd then find (or not find) the edge I linked above and further [assess the edge](https://github.com/converged-computing/rainbow/blob/bf92d293ce531e682685477f729d18f5857059d4/plugins/backends/memory/dfs.go#L144) if it matches. Then the slot either is satisfied `slotNeeds.Satisfied` (meaning all the containment resources _plus_ subsystem requirements) or not.

**Reply by vsoch** [reply]
And that edge is possible because when you register the subsystem, you include edges to it. E.g., for [ior here](https://github.com/converged-computing/rainbow/blob/bf92d293ce531e682685477f729d18f5857059d4/docs/examples/scheduler/cluster-io-subsystem.json#L137-L141). 

Another cool idea I had when I was working on that is, instead of needing to have match algorithm plugins, you could have something like a json string that could be queried, e.g., https://github.com/itchyny/gojq. That would just be a more flexible strategy to do that - I didn't implement it because I figured it's not needed yet, and fluxion should be ready soon. But I don't like my current match approach, which is OK because it will work for a prototype, but I think I can do something more flexible and elegant.

**Reply by vsoch** [reply]
I haven't written this up because I don't want to overwhelm people, but the current implementation will work for our descriptive expression next experiment, specifically the same thing (a bunch of lammps images and nodes) but with the scheduler. What we can do:

1. Create a cluster in Kubernetes with different node types (this could be an HPC cluster too, but Kubernetes is easier for me)
2. Define subsystems (the JGF) for each attribute family that was previously just matched to as key value pairs
3. Take each previous compatibility spec that describes the guts of a container, and just dump it into the jobspec format we have here.
4. Submit the jobs to rainbow, and rainbow will use the logic to choose nodes.

And then we can do that for two cases, one with the extra metadarta, and one without, and (very likely) we will see the same thing as before - without it you get a lot of mis-matches so MPI or the host OS ABI throws up on you.

**Reply by vsoch** [reply]
And instead of running MiniCluster on the fly, what we will instead do is have them _be_ our HPC clusters on these nodes. So technically speaking, it will look the same as it does in HPC, just running in Kubernetes. At least that's the high level idea.

**Reply by trws** [reply]
I think I didn't express my question well, that's all good information but wasn't quite what I meant to ask for.  In this syntax, how does the system know which vertex in the containment graph the edge is meant to come from? Like will this look for a `node->shm` link, or a `core->shm` link or what? I don't see where the structure is specified I guess, or is it not and it's an entirely separate match that must also be found but need not be connected?

**Reply by vsoch** [reply]
It’s at the same level of the slot, so wherever the slot is set to be (up to the user).

**Reply by trws** [reply]
Oh, ok, so this would be looking for an edge from the node to the shm because the slot is below the node?

**Reply by vsoch** [reply]
I think I got that right? A node _with_ I read as "I want this node _with_ this resource..." so a slot means you look for the resources _at_ that level, and then if there are nested stuffs below it (cores in the above - "I want a node _with_ cores" which are a child resource) that would technically be a child.  So:

- Task resources defined in slot are at the level where the slot is defined (node for the above) - read as "a node _with_ x"
- Slot resources that are (by definition) children of the slot are child vertices in the same subsystem.

Does that make sense (or did I get that wrong)?

**Reply by trws** [reply]
Yeah, that's right.  I've never thought of splitting it up quite this way so it didn't click without the extra explanation. The slot is sort-of a non-entity, it's a passthrough container that denotes where the tasks are, and things under it (dominated by is probably the right graph-centric term) are marked exclusive, while things outside it are left non-exclusive.  So I guess this would be equivalent, it just never occurred to me to allow splitting up the resource query quite this way, it's interesting.

**Comment by vsoch** [comment]
For the jobspec command, most of the examples I've seen are like "app" or just a single executable with args. It looks like command is a list of strings:

![image](https://github.com/flux-framework/flux-core/assets/814322/551302e9-3c15-4ff0-9ec7-942a2c6ffeb5)

So I'm thinking we need an ability (however it's done) to handle:

1. a custom script
2. a specification to run flux batch (also with a custom script).

For example, for the flux operator I can provide a single command, e.g.,:

```yaml
apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 4
  containers:
  - image: ghcr.io/converged-computing/distributed-fractal
    command: fractal leader
```
And that would map easily to what we have now, but there are several cases this doesn't well address:

- writing a _set_ of commands for a script that is given to flux submit (e.g, to allocate something for different ranks to do). The example here is usernetes.
- using flux batch and at the top level spinning off different flux allocations (maybe even with different schedulers)!

Also, for most complex start logic, especially if containers are involved, it's likely going to be the case that the user wants a multi-lined, custom entrypoint. Right now they would need to build that into the container, or (for the flux operator) a workaround would be to have it written in a pre or init command block, and then set the command to be to use it.

I think we need to make it (for the user) stupid easy to get either a multi-line script or batch - and although I'd like to write some kind of tool to better orchestrate that, we can assume there are simple cases of multi-line that already warrant needing this. For example, for the flux operator I can do:

```yaml
apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: flux-sample
spec:
  size: 4
  containers:
  - image: ghcr.io/converged-computing/distributed-fractal
    commands:
      script: |
        #!/bin/bash
        echo "This is task"
        if [[ "\${FLUX_TASK_RANK}" == "0" ]]; then
           fractal leader --force-exit --host 0.0.0.0:50051
        else
           fractal worker --force-exit --host flux-sample-0.flux-service.default.svc.cluster.local:50051
        fi
```

Right now I require the user to escape envars, otherwise they get evaluated, but you could imagine that being more elegant. I'm not sure it belongs here, but (for the associated tool to use in batch or a script that accounts for rank tasks) I'd like to be able to easily ask for things like:

- start another broker with this setup
- use this topology mapping for that setup
- wait here until the other tasks that I just "did the thing for" are ready
- submit these jobs A and wait for them before I do B

I know the last one works with waitable, but I'm thinking of wanting something that looks more similar to a very simple /dumb specification of a sequence of tasks and dependencies that doesn't require the user to know the nuances of flux flags. Anyway, for this particular point, I'm suggesting we have something like:

```yaml
tasks:
    - slot: default
      script: |
        #!/bin/bash
        echo "The answer my friend"
        echo "is blowing in the wind"
        echo "The answer is blowin' in the wind"
      count:
         per_slot: 1
```
And that way I can more easily write a job for, rainbow, that doesn't require my special script to exist there (but only the software needed for it).
