### ISSUE TITLE
Single application with multiple slots

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#2141]
An interesting jobspec question came up today, can we support running a single application on multiple slot types at the same time.  I don't see why not necessarily but I don't think the jobspec currently supports this.  The specific use-case was the desire to have one rank per GPU, with a core each, and an MPI rank that used the rest of the cores on each node but no GPU.

**Comment by trws** [comment]
I suppose the question is, should this be valid?

(forgive the pseudo-jobspec)

```yaml
type: node
count: 15
with:
  - type: slot
     label: task
     with: GPU + 1 core
  - type: slot
     label: task
     with: CORES
```

**Comment by dongahn** [comment]
From the graph matching scheduling point of view, this will certainly make the algorithm much more complex. (I am not even sure if it is possible to do this with one-pass algorithm we use. This is something that one needs to sit down and tries to actually code it). 

If the per-node requirement is given in aggregate, matching can be simpler of course and the matching service can generate an R that meets the overall requirement (with no fine grained slot info). 

```yaml
type: node
count: 15
with:
  - type: slot
    label: tasks
    with: GPU + 1 core + CORES
```

I don't know if such an R cab be further divvied up by the execution system to do the final mapping/binding...

Certainly a use case to think about.

Do apps people already have existing examples? Or is this theoretical? This probably requires them to write heterogenous MPI communitation patterns using groups and such...
