### ISSUE TITLE
jobspec resource and slot nesting and v1

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#2214]
In working up #2213, I realized that the current jobspec command and the discussions of V1 in flux-framework/rfc#149 all produce jobspec with the slot inside the node resource.  I recall having discussions about this, but it may cause problems if we can't have the slot outside the node for making both the srun and the new arguments behave.

The main issue is that if the slot can't be on the outside, then the number of Nodes can't be controlled by the number of slots, which is proving to be a non-trivial wrench in the works.  Can anyone remember what the specific issue was with allowing the slot on the outside?  There doesn't seem to be an issue with requiring the node to be either first outside or first inside, or that there only be one if it's inside, but having it outside only is causing heartburn.

**Comment by SteVwonder** [comment]
> Can anyone remember what the specific issue was with allowing the slot on the outside?

IIRC, the idea for having it outside was to have the default/forced behavior be core-level scheduling.  That is, unless you explicitly put `exclusive: true` under the node, you would only exclusively get cores.  This is useful at the sub-instance level, where you may want to pack a bunch of jobs on a single node.  If you only allow the node inside a slot, that functionality breaks (although, now that I think about it, you could always put `exclusive: false` under the node which is under the slot).  It also allowed the ordering of types to remaining constant (i.e., core would always be under slot and node would just be optional), but I'm not sure if that ends up making the implementation simpler or not.

> There doesn't seem to be an issue with requiring the node to be either first outside or first inside, or that there only be one if it's inside, but having it outside only is causing heartburn.

I think simpler is better for V1.  So if we can get away with just having it on the outside, then I am leaning towards that.  If we can refactor `flux-jobspec` to handle all of the cases it handles now but with the `slot` on the outside, I think that is a good indicator that that is a good way to go.  Otherwise, having it in either position is probably the way to go.

**Comment by SteVwonder** [comment]
Ah.  I've got the reason for having the node outside the slot.  Consider `srun -n4 -N2 -c8 myApp`.  

With node outside the slot, you can specify this as:

```yaml
- type: node
  exclusive: true
  count: 2
  with:
  - type: slot   
    name: foo
    count: 4
    with:
    - type: core
      count: 8
tasks:
- command: foo
  slot: foo
  count:
    per_slot: 1
```
and it kind of naturally just falls out of the specification that Slurm uses.

You can closely approximate it with:
```yaml
- type: slot
  name: foo
  count: 1
  with:
  - type: node   
    count: 2
    with:
    - type: core
      count: 16
tasks:
- command: foo
  slot: foo
  count:
    total: 4
```
but they technically aren't semantically equivalent.  I'm not sure that we care about preserving the semantics perfectly though.
