### ISSUE TITLE
flux-shell: mystery segfault

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2483]
I noticed I get one of these in my kernel dmesg whenever I run `make check` on my Ubunut 18.04 x86_64 test systems
```
[278831.740652] flux-shell[9652]: segfault at 0 ip 00007f01332104b0 sp 00007ffe7423e320 error 4 in libc-2.27.so[7f013312b000+1e7000
```
 
I narrowed it down to
```console
$ cd t
$  make check TESTS=python/t0010-job.py
```

The tests pass.

**Comment by garlick** [comment]
Submitting the test input `t/jobspec/valid/basic_v1.yaml` seems to cause it:
```yaml
version: 1
resources:
  - type: slot
    count: 1
    label: task
    with:
      - type: core
        count: 1
tasks:
  - command: app
    slot: foo
    count:
      per_slot: 1
attributes:
  system:
    duration: 0
```
```console
$ flux python t/jobspec/y2j.py <t/jobspec/valid/basic_v1.yaml >j
$ flux job submit j
8716183142400
$ flux job attach -EX 8716183142400
job-event: 0.000 submit {"userid":5588,"priority":16,"flags":0}
job-event: 0.013 depend
job-event: 0.016 alloc {"note":"rank0/core0"}
job-event: 0.022 start
flux-job: task(s) exited with exit code 139
job-event: 0.212 finish {"status":35584}
job-event: 0.217 release {"ranks":"all","final":true}
job-event: 0.218 free
job-event: 0.218 clean
exec-event: 0.017 init
exec-event: 0.019 starting
exec-event: 0.021 running
exec-event: 0.046 input-ready {"leader-rank":0}
exec-event: 0.046 output-ready
exec-event: 0.212 complete {"status":35584}
exec-event: 0.212 cleanup.start {"ranks":"all"}
exec-event: 0.213 cleanup.finish {"ranks":"all","rc":0}
exec-event: 0.214 done
```
