### ISSUE TITLE
content-s3: add TOML configuration

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2983]
This is a placeholder for designing TOML configuration for the `content-s3` module proposed in #2975.

At a minimum, the module will need to know a URI for the service, a user name, and a bucket name.  See #2982 for the issue of credential storage.

**Comment by garlick** [comment]
As noted in #2982 we need a pointer to a credential file here, e.g.
```toml
[content.s3]

credential-file = "/etc/flux/s3/credential"
```

**Comment by garrettbslone** [comment]
Proposed design for config:
```
[content.s3]

credential-file = "/etc/flux/s3/credential"
S3_HOSTNAME = "https://my-host.com:9000"
S3_BUCKET = "my-bucket"
virtual-host-style = true
```
with the credential file containing:
```
[content-s3]

S3_ACCESS_KEY_ID = "my-access-key"
S3_SECRET_ACCESS_KEY = "my-secret-key"
```

**Comment by garlick** [comment]
Since we're already in an "s3" TOML namespace here, I'd suggest we strip the `S3_` prefix from kek names, go lower case, and change the underbards to hyphens (to be more like other toml config).

Also instead of `hostname` maybe we could use `uri`?

So maybe
```toml
credential-file = "/etc/flux/s3/credential"
uri = "https://my-host.com:9000"
bucket = "my-bucket"
virtual-host-style = true
```

And for the credential file, I don't think we need the enclosing table.  How about we keep it simple with
```toml
access-key-id = "my-access-key"
secret-access-key = "my-secret-key"
```
