### ISSUE TITLE
exec: jobspec with multiple slots, each with own application

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3403]
After speaking with the [CODAR](https://github.com/CODARcode?type=source) folks, they have a lot of use cases that require the specification of co-scheduling requirements within the same jobspec (i.e., they can't always submit multiple jobs).  I wanted to open an issue to track what still needs to be done within Flux to handle a use case like this.

As a specific example, they want to request that an MPI simulation code and an MPI analysis code are spun up on the same set of nodes, with a certain amount of resources per node given to each application.  Both applications each need their own, separate MPI communicator.

Strawman jobspec request (lightly modified version of Use Case 2.4 from RFC14):
```yaml
version: 999
resources:
  - type: node
    count: 10
    with:
      - type: slot
        label: simulation
        count: 4
        with:
          - type: core
            count: 1
          - type: gpu
			count: 1
		  - type: memory
			count: 4
			unit: GB
      - type: slot
        label: analysis
        count: 1
        with:
          - type: core
            count: 20
          - type: memory
            count: 24
            unit: GB
tasks:
  - command: [ "sim-mpi.exe" ]
    slot: simulation
    count:
      per_slot: 1
  - command: [ "analysis-mpi.exe" ]
    slot: analysis
    count:
      per_slot: 1
attributes:
  system:
    duration: 3600.
    cwd: "/home/flux"
    environment:
      HOME: "/home/flux"
```
