### ISSUE TITLE
add queue specific resource constraint/property for partitioned resources

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4438]
Problem:  to implement simple "partitions", we can use the `jobspec-default` plugin to set queue-specific properties that match properties set in _R_ that designate a partition.   So for example, if the user requests a queue named "debug", and we could configure 
```toml
[queues.debug.policy.jobspec.defaults]
system.constraints.properties = [ "debug" ]
```
However,
- The jobspec `properties` constraint operator value is defined as an array, but `jobspec-default` would not set the array if it already exists in the jobspec.
- a user could set a queue specific property and then get access to a partition wtihout picking up the queue specific limits

See also [RFC 31](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_31.html)
