### ISSUE TITLE
man5: newline not allowed in hosts bootstrap table

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#5249]
Hola! I'm testing out custom flux broker bootstrap configs, and reading from here:

And when I create an example as follows:

```toml
imp = "/usr/libexec/flux/flux-imp"

[access]
allow-guest-user = true
allow-root-owner = true

[resource]
path = "/etc/flux/system/R"

[bootstrap]
curve_cert = "/etc/curve/curve.cert"
default_port = 8050
default_bind = "tcp://eth0:%p"
default_connect = "tcp://%h.flux-service.flux-operator.svc.cluster.local:%p"
hosts = [
    {   
        host="flux-sample-0",
        bind="tcp://eth0:8050",
        connect="tcp://flux-sample-0.flux-service.flux-operator.svc.cluster.local:8050"
    },
    { host="flux-sample-[1-3]"},
]

[archive]
dbpath = "/var/lib/flux/job-archive.sqlite"
period = "1m"
busytimeout = "50s"
```

I get this bug:

```console
flux-broker: Config file error: /etc/flux/config/broker.toml:17: newline not allowed in inline table
```
I tried a few variations (with newlines) and the only one that worked required all the attributes in the curly braces to be on the same line, e.g.:

```console
[exec]
imp = "/usr/libexec/flux/flux-imp"

[access]
allow-guest-user = true
allow-root-owner = true

[resource]
path = "/etc/flux/system/R"

[bootstrap]
curve_cert = "/etc/curve/curve.cert"
default_port = 8050
default_bind = "tcp://eth0:%p"
default_connect = "tcp://%h.flux-service.flux-operator.svc.cluster.local:%p"
hosts = [{host="flux-sample-0", bind="tcp://eth0:8050",connect="tcp://flux-sample-0.flux-service.flux-operator.svc.cluster.local:8050"},
         {host="flux-sample-[1-3]"}]
[archive]
dbpath = "/var/lib/flux/job-archive.sqlite"
period = "1m"
busytimeout = "50s"
```
My versions are slightly old so this might be a bug that was fixed?

```
# flux version
commands:               0.49.0-225-g53e087510
libflux-core:           0.49.0-225-g53e087510
libflux-security:       0.7.0
build-options:          +caliper+systemd+hwloc==2.1.0+zmq==4.3.2
```
I'm thinking to address this, either it should be allowed to span multiple lines (it looks nicer, matches the examples in the docs) OR the example here https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man5/flux-config-bootstrap.html#example might be updated to not include the newlines. For the time being I-will-pack-them-close-together-like-sardines-so-close-they-can-smell-eachother Thank you!
