### ISSUE TITLE
Is it possible to use flux-core on Github CI

### ISSUE THREAD

**Issue by jan-janssen** [flux-framework/flux-core#5362]
I created a small test case but unfortunately I am not able to initialise flux using `flux start` I always get an `Exception caught: rsmi_init.` I would like to integrate flux in tests on other repositories, but I struggle to understand how `flux start` creates the interactive session and how this could be integrated in the Github CI. My example repository is:  
https://github.com/jan-janssen/flux-github-ci

**Comment by grondo** [comment]
The key is to execute your tests as the argument to `flux start`. Without any arguments `flux start` launches an interactive shell -- I'm not sure what would happen in a non-interactive environment like Github CI, possibly a hang or an error like you are seeing.

In your example repo above, you run `flux start`, then `flux submit` in a separate shell. This won't work because only the shell or program started by `flux start` has access to the test instance that has been created.

The `rmsi_init` error is from hwloc, I'm not sure why you see `Exception caught` with it, when I've seen it, it is a harmless error message.

For more background, `flux start` starts a flux instance (mostly for testing) with one or more brokers (e.g. you can start a test instance with 4 brokers with `flux start --test-size=4`) and launches an interactive shell with access to that instance (by setting `FLUX_URI` to the URI of the rank 0 broker for the newly created instance). This allows multiple instances to be started on a single system in parallel without interfering with each other.  If `flux start` is given an argument then this script is run instead of an interactive shell, and the instance terminates automatically when the script is complete (we call this an "initial program" and it works very much like a batch script).

The flux-core testsuite and the tests of many of its subprojects use `flux start` to run automated tests in CI. Our testsuite is based on [sharness](https://github.com/felipec/sharness), I'd be happy to go into more detail how it works if you'd like. You could then decide if borrowing the framework would work for your testing purposes.

**Comment by jan-janssen** [comment]
Oh great, I thought the error message meant that flux was not able to start the broker. All I had to do was change the `run: |` line to `run: >`. Just in case somebody else wants to reproduce the environment: 
```
name: Flux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        python-version: "3.11"
        mamba-version: "*"
        channels: conda-forge
        miniforge-variant: Mambaforge
        channel-priority: strict
        auto-update-conda: true
        environment-file: "environment.yml"
    - name: Install flux
      shell: bash -l {0}
      run: mamba install -y flux-core
    - name: Test
      shell: 'script -q -e -c "bash -l {0}"'
      timeout-minutes: 5
      run: >
        flux start
        flux submit sleep 1
        sleep 2
        flux jobs -a
        flux resource list
```
