### ISSUE TITLE
cgroups memory limit does not cover memory allocated by ROCm hipMalloc()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5949]
Problem: Memory allocated by ROCm [hipMalloc()](https://rocm.docs.amd.com/projects/HIP/en/latest/doxygen/html/group___memory.html) is not subject to memory limits.

When flux runs with
```toml
[systemd]
enable = true
[exec]
service = "sdexec"
[exec.sdexec-properties]
MemoryMax = "95%"
```
We observed that memory allocated by `hipMalloc()` is not accounted for in the job's cgroup, and the user is able to exceed `MemoryMax` and run the kernel out of memory.

An [issue](https://ontrack.amd.com/browse/LLNLA-282`) was opened with AMD (though not public at this time).
