### ISSUE TITLE
resource: improve error message when excluded rank doesn't appear in R or `resource.config`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6136]
With a resource section like the following:
```toml
[resource]
exclude = "host[1,1001-1002]"
norestrict = true

[[resource.config]]
hosts = "host[1001-1002]"
cores = "0-95"

[[resource.config]]
hosts = "host[1003-1100]"
cores = "0-95"
gpus = "0-3"

[[resource.config]]
hosts = "host[1003-1100]"
properties = ["pbatch"]
```

Flux failed to start with only the following error as a clue:
```
broker.err[0]: rc1.0: flux-module: load resource: Invalid argument
```

Probably the error is that `host1` is not in `resource.config` but is excluded? The error from the instance should be improved.
