### ISSUE TITLE
add table for job validators in broker config

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6298]
Problem: Configuration for job validator plugins currently has to be passed as options on the `flux job-validator` command line. Those options have to in turn be added to the ingest module config. With many validators, this could potentially get unwieldy and is especially difficult to pass along via the `--conf` option of `flux batch` and `alloc` if necessary.

Perhaps a table in the broker config TOML could be reserved for validator plugin configuration. e.g. either `[validator.plugin-name]` or `[ingest.validator.plugin-name]`.

This would allow, for example, the `require-instance` plugin to be configured via:

```toml
[validator.require-instance]
minnodes = 16
mincores = 768
```

Thoughts on which table to reserve, and how to document it?

**Comment by garlick** [comment]
Good idea.  `[ingest.validator.plugin-name]` makes sense to me, documented in  [flux-config-ingest(5)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man5/flux-config-ingest.html).

So the overall config might look like
```toml
[ingest.frobnicator]
plugins = [ "defaults" ]

[ingest.validator]
plugins = [ "jobspec", "feasibility" , "require-instance"]
args =  [ "--require-version=1" ]

[validator.require-instance]
minnodes = 16
mincores = 768
```
