### ISSUE TITLE
TOML config updates can overwrite tables

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#6396]
One feature of Flux TOML configuration is that a set of `*.toml` files can be read in and the configuration is aggregated into a single table (or JSON object internally).

Given this, it may be enticing to attempt to update a single config key in a table by dropping in a TOML file that will be read last in lexical order. However, this doesn't work because `json_object_update()` is called so only top-level keys are updated. Thus, the result of this practice will be to _replace_ the config table that was meant to be updated. For example, if we have the following job-manager config in the main `config.toml`:

```toml
[job-manager]
inactive-age-limit = "30d"
plugins = [ { load = "perilog.so" } ]

[job-manager.prolog]
timeout = "1m"
per-rank = true

[job-manager.epilog]
timeout = "15s"
per-rank = true

[job-manager.housekeeping]
release-after = "30s"
```

and we want to update the prolog timeout for instance with a drop in config:

```toml
[job-manager.prolog]
timeout = "30m"
```

What actually happens is the entire `job-manager` table is replaced and you end up with:
```
$ flux config get --config-path=system | jq '."job-manager"'
{
  "prolog": {
    "timeout": "30m"
  }
}
```
