### ISSUE TITLE
flux prolog not killed on cancel

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#6465]
My prolog and epilog seem to be running, but when I tested cancel, the nodes are still allocated and:

![image](https://github.com/user-attachments/assets/0cc2710b-32e7-4599-af71-b1cef73f5396)

My imp.toml:

```toml
[exec]
allowed-users = [ "flux", "ubuntu", "root" ]
allowed-shells = [ "/usr/libexec/flux/flux-shell" ]

[run.prolog]
allowed-environment = [ "FLUX_*" ]
allowed-users = [ "flux", "ubuntu", "root" ]
path = "/etc/flux/system/prolog"

[run.epilog]
allowed-environment = [ "FLUX_*" ]
allowed-users = [ "flux", "ubuntu", "root" ]
path = "/etc/flux/system/epilog"
```

and maybe this is my fault for setting a high timeout?

Note that it looks like this issue: https://github.com/flux-framework/flux-core/issues/6296 and I'm indeed running flux with systemd!

```toml
[job-manager]
plugins = [
  { load = "perilog.so" }
]

[job-manager.prolog]
per-rank = true
timeout = "10m"

[job-manager.epilog]
per-rank = true
timeout = "5m"
```
I commented out the timeouts for another try (I thought it was a "kill the job if it's not done in this time," which I don't want) but it didn't change the behavior - I issue a cancel and the nodes remain allocation. I tried a combination of trying to kill things with systemd, and eventually seemed to get my little cluster back! I didn't get the full event log (and it's gone now):

![image](https://github.com/user-attachments/assets/073d3db0-2c0d-4cb6-84fa-0dc55772ccd7)

Is there something else I should try? Sorry for all the issues, let me know if you don't want me to open them!

**Comment by garlick** [comment]
Keep the issues coming @vsoch!

#6296 refers to a configuration where the prolog/epilog are run as systemd units, but that doesn't apply here since you're running them directly (e.g. as direct children of the broker):
```toml
[run.prolog]
allowed-environment = [ "FLUX_*" ]
allowed-users = [ "flux", "ubuntu", "root" ]
path = "/etc/flux/system/prolog"

[run.epilog]
allowed-environment = [ "FLUX_*" ]
allowed-users = [ "flux", "ubuntu", "root" ]
path = "/etc/flux/system/epilog"
```

What versions of flux-core and flux-security are you running?

The scheme for signaling imp-run processes changed in flux-core-0.68.0 + flux-security-0.13.0
