### ISSUE TITLE
idea: add convenience configuration/hostlist plugins

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#6651]
Problem: most sites will have a configuration management "source of truth" that is used to generate the Flux hosts table, resource attributes, etc for the flux config.

Could we perhaps make life easier (and less error prone) by providing a way to get hostlists from plugins (for things like [LDAP netgroup](https://ldapwiki.com/wiki/Wiki.jsp?page=Netgroup) or [genders](https://github.com/chaos/genders))?

For example, where a hostlist string appears in our config like
```toml
[[resource.config]]
hosts = "picl[1-7]"
properties = ["batch"]
```
Allow an expression in place of the hostlist, like
```toml
[[resource.config]]
hosts = "genders:batch"
```
Then when parsing the configuration, the hostlist would be obtained by calling out to the plugin scheme with the path as input?

I'm not sure if this would be useful or not.  Maybe it would have Flux treading in the configuration management domain when it should stay it its lane.  Anyway, just throwing it out there :shrug:
