### ISSUE TITLE
clang testing on travis

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#737]
We lost the recent clang testing when llvm took down their debian repo, so no ASan testing for things like #736, but there's a binary package we can use now.  Below is a snippet from RAJA's .travis.yml adding the three most recent clangs to the test matrix:

```yaml
   - compiler: clang-3.6
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-5
     env: 
         - COMPILER=$HOME/llvm/clang+llvm-3.6.0-x86_64-linux-gnu/bin/clang++
         - DOWNLOAD=http://llvm.org/releases/3.6.0/clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
   - compiler: clang-3.7
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-5
     env: 
         - COMPILER=$HOME/llvm/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++
         - DOWNLOAD=http://llvm.org/releases/3.7.0/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
   - compiler: clang-3.8
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-5
     env: 
         - COMPILER=$HOME/llvm/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang++
         - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/llvm/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/lib
         - DOWNLOAD=http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
```
